### ISSUE TITLE
implement all use cases in UCD after 2016-10-07 (back-end)

### ISSUE THREAD

**Issue by eternalphane** [BUAA-Database-Admin/school-management-system#1]
# Task List
## Student
- [x] Select Classes
- [x] Check Grades
- [x] Type-in Personal Information
- [x] View Classes Information
## Teacher
- [x] Type-in Grades
- [x] Type-in Personal Information
- [x] View Classes Information
## SysAdmin
- [x] Add Teachers
- [x] Add Students
## SchoolAdmin
- [x] Add Courses
- [x] Add Departments
